module xor_gate_tb;
  reg a,b;
  wire y;
   xor_gate dut (.a(a), .b(b), .y(y));
      initial begin 
        a=0; b=0;
      #10 a=0; b=1;
      #10 a=1; b=0;
      #10 a=1; b=1;
      #10; 
      $finish;
      end
 
      initial begin
      $monitor($time,"a=%b,b=%b,y=%b",a,b,y);
      end
 
endmodule
